version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: ghcr.io/wy-bbw/trollsar_builder
        auth:
          username: wy-bbw
          password: $GITHUB_REGISTRY_PASSWORD
    steps:
      - checkout
      - when:
          condition:
            or:
              - equal: [ develop, << pipeline.git.branch >> ]
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: build trollsar
                command: |
                  mkdir build
                  cd build
                  cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -G Ninja
                  cmake --build . --parallel
            - run:
                name: run tests
                command: |
                  ctest --test-dir build --output-junit results.xml
