version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine:
      image: ghcr.io/wy-bbw/trollsar_builder:latest
    steps:
      - checkout
      - when:
          condition:
            or:
              - equal: [ develop, << pipeline.git.branch >> ]
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: build optix
                command: |
                  ls
                  cd external/optix/7.5/SDK
                  mkdir build
                  cd build
                  cmake ..
                  make -j 12
            - run:
                name: build trollsar
                command: |
                  mkdir build
                  cd build
                  conan install .. -r conancenter --build=missing --profile ../config/conan/profiles/clang13
                  cmake .. -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_C_COMPILER=gcc-12
                  make -j 16
            - run:
                name: run tests
                command: |
                  ctest --test-dir build --output-junit results.xml