# This is a basic workflow to help you get started with Actions

name: test

  # Controls when the workflow will run
on: [push, workflow_dispatch]
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [master, develop]
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  #jobs:
  #  # This workflow contains a single job called "build"
  #  build:
  #    # The type of runner that the job will run on
  #    runs-on: ubuntu-latest
  #
  #      # Steps represent a sequence of tasks that will be executed as part of the job
  #    steps:
  #      - name: setup dependencies
  #        run: sudo apt install libboost-all-dev
  #
  #
  #      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #      - name: checkout repository
  #        uses: actions/checkout@v2
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: sudo apt update && sudo apt upgrade

      - name: install trollsar dependencies
        run: sudo apt install libboost-all-dev

      - name: checkout repository
        uses: actions/checkout@v2

      - name: install cuda
        uses: Jimver/cuda-toolkit@v0.2.4
        id: cuda-toolkit
        with:
          cuda: '11.2.2'
      
      - name: install optix dependencies
        run: sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev xorg-dev 

      - name: cpuinfo
        run: cat /proc/cpuinfo 

      - name: build optix
        run: |
          cd optix/7.4/SDK/
          mkdir build
          cd build
          cmake .. -DCUDA_CUDA_LIBRARY=${{steps.cuda-toolkit.outputs.CUDA_PATH}}/lib64/stubs
          make -j 12

      - name: build trollsar
        run: |
          mkdir build
          cd build
          cmake ..
          make -j 4

      - name: run tests
        run: |
          ctest --test-dir build
