# This is a basic workflow to help you get started with Actions

name: test

  # Controls when the workflow will run
on: [push, workflow_dispatch]
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [master, develop]
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  #jobs:
  #  # This workflow contains a single job called "build"
  #  build:
  #    # The type of runner that the job will run on
  #    runs-on: ubuntu-latest
  #
  #      # Steps represent a sequence of tasks that will be executed as part of the job
  #    steps:
  #      - name: setup dependencies
  #        run: sudo apt install libboost-all-dev
  #
  #
  #      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #      - name: checkout repository
  #        uses: actions/checkout@v2
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt install libboost-all-dev

      - name: checkout repository
        uses: actions/checkout@v2

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j 4
      - name: run tests
        run: |
          ctest --test-dir build
